### ISSUE TITLE
pleae open and read comments.

### ISSUE THREAD

**Issue by Mossshka** [ZygZagGaming/elemental#4]
can you please reach out to Infinite-3d and tell him that he should fix scenexe by bringing the special deminsions back?
(Sorry for all the random spam lately) @ZygZagGaming

**Comment by ZygZagGaming** [comment]
I don't know how you found this just a few days after it was created but Infinite-3d isn't on this repo. This issue (and the one you posted beforehand) are completely unrelated to the repos you put them on. Please stop harassing me.
